# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 352af79ac367fb98ea04f5caa10661dacbf4985d0ca3fbd8a0ebad7db39cf41a9491fd9547b3600e76720b1654595ab71927f58ecb241132cf63833426475361

test:
  secret_key_base: ee32a24edddb2faa56589c8fc9b83db416dbf15d57c0a78164b2f276cbdb1c6f8a79bfe7fb696d920288fe7138c4af08d39bd348af647570267e6567273a5c3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
